### PR TITLE
unicode support improvements: wider glyph, combined glyph

### PR DESCRIPTION
**Pull request by kandu**
note, this pr depends on another pr in the lambda-term project ocaml-community/lambda-term#71

* UTop_lexer: support combined glyph
* follow the api changes of zed_char and zed_string

### CODE REVIEW

**Comment by pmetzger** [comment]
I'm not sure how good I would be at reasonably reviewing this. This brings up the question of who should, or whether we need review before committing.

**Comment by diml** [comment]
I'd say it depends of the quality of service we want to provide for utop. In my opinion, utop is not a fundamental building block of the ecosystem: it is a tool human use to play with libraries but it is not something they rely on for building the software they put in production.

The most important thing to care about here is the user experience: if the behaviour of utop keeps changing all the time then that's annoying for users. Apart from that, I personally feel relax about letting motivated contributors develop their feature as long as they are reactive about providing follow up support.

However, one thing to keep in mind is the recent npm security debacle. I.e., when new contributors show up, we should eyeball their patches until we trust them.

**Comment by kandu** [comment]
For these particular PRs, we can pay attention only on the API changes. Implementation bugs are easy to fix, but a design mistake in the API will annoy us for a long period of time until next major release.

**Comment by pmetzger** [comment]
> if no one else feels comfortable reviewing such patches, I feel like we need to trust a bit more contributors who look motivated by the project

I don't disagree. I just don't want to make that decision entirely on my own. :)

**Comment by pmetzger** [comment]
> if no one else feels comfortable reviewing such patches, I feel like we need to trust a bit more contributors who look motivated by the project

I don't disagree, but I don't think I should be making that decision on my own.

**Comment by diml** [comment]
That's a fair point. Though, we need to find a good balance. I'm personally finding it hard to find time for utop, and if no one else feels comfortable reviewing such patches, I feel like we need to trust a bit more contributors who look motivated by the project. It's a small risk anyway, if it doesn't work out we can always revert the patches.

**Comment by diml** [comment]
I don't disagree either. I feel like for a project like utop, it is fine to have a more dynamic approach and rely on publishing bugfixes quickly.

@kandu, I suggest that you merge this patch once you are satisfied with your testing. I had a quick look and didn't see anything chocking.

**Comment by pmetzger** [comment]
So if this is merged now, should we consider a new release?

**Comment by kandu** [comment]
I think It's time to make a new release.

**Comment by pmetzger** [comment]
So please do!

**Pull request merged**
