### PR TITLE
remove more camlp4 remnants

### PR DESCRIPTION
**Pull request by kandu**
After PR #290 was merged, there are still some remnants left in the lexer.
cc @XVilka

### CODE REVIEW

**Comment by pmetzger** [comment]
Looks fine to me. The CI failure seems to have been a fluke; I restarted that job just in case. Do all tests pass?

@diml, does this look good to you? If so we can merge it.

**Comment by pmetzger** [comment]
The CI failure is certainly a fluke, FWIW.

**Comment by XVilka** [comment]
After this one merged, then https://github.com/ocaml-community/utop/issues/289 should be closed as well.

**Comment by pmetzger** [comment]
@XVilka would you like to do an informal review of the patch while we're waiting for @diml?

**Comment by XVilka** [comment]
@pmetzger I checked it already, it is good. Too bad I forgot those in the first place.

**Comment by pmetzger** [comment]
Merged! Thanks, @kandu!

**Pull request merged**
