### PR TITLE
Added tips for simple prompt without fancy features

### PR DESCRIPTION
**Pull request by mars0i**
This is in the Prompt section of README.md.  I'm submitting a separate PR for an analogous change to the man page so you can easily reject one PR and accept the other if you want.

### CODE REVIEW

**Comment by mars0i** [comment]
Oh, right--all commits get added into the PR.  So it's one PR with two commits.

**Comment by pmetzger** [comment]
@mars0i FYI, you should have done your work on a branch rather than on your master. (This is a common mistake when working with github.) Please don't make any stray commits to master until this is integrated (or until you close it and re-open with a pull request from a branch.)

**Comment by pmetzger** [comment]
@diml This seems like a fine documentation change to me. Do you see any reason I shouldn't merge it?

**Comment by diml** [comment]
nope, LGTM :)

**Comment by mars0i** [comment]
FYI, you should have done your work on a branch rather than on your master. 
    (This is a common mistake when working with github.)

@pmetzger, ah, that's right.  Sorry about that.

**Pull request merged**
