### PR TITLE
Correct quoting for Windows command shell (#272)

### PR DESCRIPTION
**Pull request by db4**

### CODE REVIEW

**Comment by pmetzger** [comment]
@db4 You're pretty certain this works?

@diml Should we merge?

**Comment by db4** [comment]
> @db4 You're pretty certain this works?

I have nothing to add to the discussion in https://github.com/ocaml-community/utop/issues/272 You asked me to do a pull request and I did just that.

**Comment by pmetzger** [comment]
Okay, unless @diml objects in the next few days I'll merge this.

**Comment by diml** [comment]
Yep, let's merge

**Pull request merged**
