### PR TITLE
Fix build on 4.12

### PR DESCRIPTION
**Pull request by emillon**
On 4.12, `Typemod.type_structure` does not take a location argument anymore (see ocaml/ocaml#9974). This fixes the build with the 4.12 branch.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Any chance this could be merged @kandu

**Comment by emillon** [comment]
Merging this to unblock the 4.12 release

**Comment by kandu** [comment]
Hi, @emillon and @kit-ty-kate. Thanks for your recent work on utop.
I got burnt half a year ago, and at least another half a year is needed to heal the wound.
So my participation will be low for a while. See you later~

**Comment by emillon** [comment]
:+1: take care :heart: ! No problem to keep the lights on wrt ocaml changes (I have no experience with emacs so I generally don't answer on the corresponding PRs)

**Comment by pmetzger** [comment]
@kandu Do you wish to be removed from the code owners list?

**Comment by kandu** [comment]
@pmetzger That's a good idea.

**Pull request merged**
